### ISSUE TITLE
Improve the Help page

### ISSUE THREAD

**Issue by ShishirBhandari** [ShishirBhandari/mandelbrot-set-generator#11]
Make the help page look good.
The information has already been added to the `help.html` file but it doesn't look quite good.

## Tasks:
- Use the content already present in the `help.html` file and make it look **pretty.** You can rewrite the file from scratch if you want.
- You can use your own creativity and art.
- You can add other information as well if you want.

## Note
- Open a PR on the dev branch.
- PR should contain only one commit i.e. squash everything into one commit.

**Comment by jasleen101010** [comment]
HI @ShishirBhandari ! I would like to work on this issue if its available. Please assign this to me :D

**Comment by ShishirBhandari** [comment]
okay,
assigned to @jasleen101010
