### ISSUE TITLE
Improve the homepage design without affecting current functionalities

### ISSUE THREAD

**Issue by ShishirBhandari** [ShishirBhandari/mandelbrot-set-generator#14]
- Current homepage design is functional but not that attractive.
- It can be made more attractive and user friendly

Tasks
- Add/Modify the CSS to make it look attractive
- HTML can be modified without affecting the current functionalities.
- Open a PR on the dev branch and add screenshots of the modified design.

**Comment by torendo** [comment]
Hi! May I take this one? Please, assign it to me.

**Comment by Aniumbott** [comment]
shall I ?

**Comment by ShishirBhandari** [comment]
I have assigned this issue to @torendo on the "first come... first serve" basis.

**Comment by ShishirBhandari** [comment]
hey @Aniumbott , you can take another issue ([Issue 16](https://github.com/ShishirBhandari/mandelbrot-set-generator/issues/16)) if you want.
