### ISSUE TITLE
Improve the help page design

### ISSUE THREAD

**Issue by ShishirBhandari** [ShishirBhandari/mandelbrot-set-generator#16]
- Improve the help page design
- Add information about the dragging and scroll zoom features on the help page.

**Comment by Aniumbott** [comment]
Can you assign this to me ?

**Comment by ShishirBhandari** [comment]
assigned to @Aniumbott

**Comment by Shrey-Nahar** [comment]
is it still open ? can I also work on this @ShishirBhandari

**Comment by ShishirBhandari** [comment]
sorry @Shrey-Nahar but @Aniumbott was already working on this.
