### ISSUE TITLE
Implement canvas image download functionality

### ISSUE THREAD

**Issue by ShishirBhandari** [ShishirBhandari/mandelbrot-set-generator#3]
Help needed in implementing download functionality for the canvas image in WebGL context.

- Download button html and css is ready: just need to enable it.
- Image Download functionality is required to be implemented in javascript.
- Refer `js/ui.js` file: line number 89.

**Comment by Thilagavathi1** [comment]
@ShishirBhandari Shall i give it a shot? please assign to me.

**Comment by Thilagavathi1** [comment]
@ShishirBhandari raised an PR for the same.Could you please verify it.

**Comment by ShishirBhandari** [comment]
Resolved, thanks to @Thilagavathi1
