### ISSUE TITLE
Current values of the sliders are not shown in the UI

### ISSUE THREAD

**Issue by ShishirBhandari** [ShishirBhandari/mandelbrot-set-generator#6]
It would be easier for the users if current values are shown when sliders are changed.

Note:
- UI display for C-real and C-Imag values is compulsary
- Other fields are optional

**Comment by jason1985** [comment]
Hi I'd like to do this if possible.

Thanks.

**Comment by jason1985** [comment]
@ShishirBhandari hi, this is what I got so far.
Let me know if this is what you're looking for and I'll work on the rest and open a PR.
Thanks.
![demo](https://user-images.githubusercontent.com/10107412/136739252-59d55330-ce88-46eb-ab4c-ef2610d8d852.gif)

**Comment by ShishirBhandari** [comment]
Hi @jason1985 ,
sorry for the late response (I was on vacation).

As for your demo, yes this is what I want. You can open the PR.

One question though - can users edit the value in the box ?

**Comment by jason1985** [comment]
No, the box only displays the current value of the slider.

**Comment by ShishirBhandari** [comment]
@jason1985, it's alright.

waiting for your PR.
