### ISSUE TITLE
Make the readme look pretty

### ISSUE THREAD

**Issue by ShishirBhandari** [ShishirBhandari/mandelbrot-set-generator#8]
Make the readme look good. The information has already been added to the README.md file but it doesn't look quite good.

Tasks:
- Use the content already present in the README.md file and make it look pretty.
- You can use your own creativity and art.
- Open a PR on the dev branch.

**Comment by nimendrak** [comment]
Hi @ShishirBhandari I am working on this issue.

**Comment by Aaryan376** [comment]
Hi @ShishirBhandari I am working on it.

**Comment by ShishirBhandari** [comment]
> Hi @ShishirBhandari I am working on it.

Hey @Aaryan376,
since @nimendrak is already working on this issue, you can work on another similar issue: [Issue 11](https://github.com/ShishirBhandari/mandelbrot-set-generator/issues/11)
